### ISSUE TITLE
current navbar as a dropdown navbar

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#319]
Currently, the navbar website is under `footer.html` and does not allow dropdown navbar. The dropdown navbar can be added via the `config.yaml` folder by adding   `sublinks` category

```
- title: Resources
   sublinks:
   - title: Guides
      url: /guides
   - title: OSPO Use Cases
      url: /use-cases
   - title: Courses
      url: /courses
```

## Action Items

Allow todogroup.org website to have a dropdown navbar
